@baseUrl = http://localhost:5000
@urlPath = api/v1
***
POST {{baseUrl}}/{{urlPath}}/register
Content-Type: application/json
Accept: application/json
withCredentials: true


{
  "email" : "",
  "username" : "",
  "password" : "",
  "avatarColor" : "",
  "avatarImage" : "",
}
